set(_AMENT_PACKAGE_NAME "go2_nav2_bridge")
set(go2_nav2_bridge_VERSION "0.3.0")
set(go2_nav2_bridge_MAINTAINER "TODO <todo@example.com>")
set(go2_nav2_bridge_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "rclcpp" "std_msgs" "tf2" "tf2_ros" "go2_interfaces")
set(go2_nav2_bridge_BUILDTOOL_DEPENDS "ament_cmake")
set(go2_nav2_bridge_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "rclcpp" "std_msgs" "tf2" "tf2_ros" "go2_interfaces")
set(go2_nav2_bridge_BUILDTOOL_EXPORT_DEPENDS )
set(go2_nav2_bridge_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "rclcpp" "std_msgs" "tf2" "tf2_ros" "go2_interfaces")
set(go2_nav2_bridge_TEST_DEPENDS )
set(go2_nav2_bridge_GROUP_DEPENDS )
set(go2_nav2_bridge_MEMBER_OF_GROUPS )
set(go2_nav2_bridge_DEPRECATED "")
set(go2_nav2_bridge_EXPORT_TAGS)
list(APPEND go2_nav2_bridge_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
