set(_AMENT_PACKAGE_NAME "go2_apportation_msgs")
set(go2_apportation_msgs_VERSION "0.0.0")
set(go2_apportation_msgs_MAINTAINER "TODO <todo@example.com>")
set(go2_apportation_msgs_BUILD_DEPENDS "builtin_interfaces" "geometry_msgs" "std_msgs")
set(go2_apportation_msgs_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(go2_apportation_msgs_BUILD_EXPORT_DEPENDS "builtin_interfaces" "geometry_msgs" "std_msgs")
set(go2_apportation_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(go2_apportation_msgs_EXEC_DEPENDS "rosidl_default_runtime" "builtin_interfaces" "geometry_msgs" "std_msgs")
set(go2_apportation_msgs_TEST_DEPENDS )
set(go2_apportation_msgs_GROUP_DEPENDS )
set(go2_apportation_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(go2_apportation_msgs_DEPRECATED "")
set(go2_apportation_msgs_EXPORT_TAGS)
